### ISSUE TITLE
My first issue

### ISSUE THREAD

**Issue by Bgaines0808** [Bgaines0808/Install-webserver-website#1]
When it came down to saving and loading the content I put in the file I had a issue. The directions said save the file as Samplepage.php. I did that and pasted the contents and it still didnt work so I can created a new file in the directory and called it newbrianfile and page worked. I saved file and the url worked after added to the end point.(ec2-54-221-163-209.compute-1.amazonaws.com/newbrianfile

This didnt work the problem was something I was over looking, moving to fast and not paying close enough attention to the directions I was supposed to check a box under additional configuration that would allow the database form to show up correctly on the page presenting the whole page after I get the "it works" the last step in the project.

**Comment by ranceforhiwd** [comment]
You should explain what those options are and why they are relevant
